
name: update-gold
author: Tom Eichlersmith
description: Commit the histograms as golden histograms

outputs:
  new-label:
    description: 'Generated Label for this new gold'
    value: ${{ steps.run-update.outputs.new-label }}

runs:
  using: 'composite'
  steps:
    - run: bash ${GITHUB_ACTION_PATH}/update-gold.sh
      id: run-update
      shell: bash 
